// 商品数组
var products = [
    { image: './images/1.png',video: './videos/1.mp4',HanLiang :12, price: 55 ,name:'加特林'},
    { image: './images/2.png',video: './videos/2.mp4',HanLiang :1, price: 120 ,name:'大礼包'},
    { image: './images/3.png',video: './videos/1.mp4',HanLiang :8, price: 18 ,name:'20发礼花/0.9'},
    { image: './images/4.png',video: './videos/1.mp4',HanLiang :6, price: 35 ,name:'36发礼花带笛音/0.9'},
    { image: './images/5.png',video: './videos/1.mp4',HanLiang :24, price: 22 ,name:'金焰三分钟'},
    { image: './images/5.png',video: './videos/1.mp4',HanLiang :20, price: 25 ,name:'笑笑三分钟'},
    { image: './images/6.png',video: './videos/1.mp4',HanLiang :24, price: 12 ,name:'孔雀开屏'},
    { image: './images/7.png',video: './videos/1.mp4',HanLiang :20, price: 18,name:'星空水母'},
    { image: './images/8.png',video: './videos/1.mp4',HanLiang :12, price: 25 ,name:'转转乐'},
    { image: './images/9.png',video: './videos/1.mp4',HanLiang :48, price: 5 ,name:'黑老大（10）'},
    { image: './images/10.png',video: './videos/1.mp4',HanLiang :40, price: 12 ,name:'020火箭（10）'},
    { image: './images/11.png',video: './videos/1.mp4',HanLiang :60, price: 12 ,name:'满地珍珠（10）'},
    { image: './images/12.png',video: './videos/1.mp4',HanLiang :60, price: 10 ,name:'金丝雨（2）'},
    { image: './images/13.png',video: './videos/1.mp4',HanLiang :60, price: 10 ,name:'雪花飞舞（2）'},
    { image: './images/14.png',video: './videos/1.mp4',HanLiang :30, price: 15,name:'多彩魔鞭'},
    { image: './images/15.png',video: './videos/1.mp4',HanLiang :36, price: 15 ,name:'金花银雨'},
    { image: './images/16.png',video: './videos/1.mp4',HanLiang :12, price: 20 ,name:'开心转盘'},
    { image: './images/17.png',video: './videos/1.mp4',HanLiang :24, price: 20 ,name:'雷神坦克'},
    { image: './images/18.png',video: './videos/1.mp4',HanLiang :36, price: 15 ,name:'笑春风'},
    { image: './images/19.png',video: './videos/1.mp4',HanLiang :16, price: 25 ,name:'年年有鱼'},
    { image: './images/20.png',video: './videos/1.mp4',HanLiang :24, price:  20,name:'大闪亮美人（100发）'},
    { image: './images/21.png',video: './videos/1.mp4',HanLiang :33, price: 15 ,name:'照明弹（4）'},
    { image: './images/22.png',video: './videos/1.mp4',HanLiang :42, price: 10 ,name:'飞毛腿（4）'},
    { image: './images/23.png',video: './videos/1.mp4',HanLiang :30, price:  8,name:'8层条鞭'},
    { image: './images/23.png',video: './videos/1.mp4',HanLiang :24, price:  10,name:'10层条鞭'},
    { image: './images/24.png',video: './videos/1.mp4',HanLiang :8, price: 35 ,name:'40公分红炮'},
    
];